### ISSUE TITLE
Add to NPM

### ISSUE THREAD

**Issue by CodersBrothers** [blockcypher/node-client#1]
Will be cool add this repo to npm for easy install in own projects :)

**Comment by seigneur** [comment]
+1

**Comment by inpay** [comment]
+1

**Comment by wescravens** [comment]
+1

**Comment by millette** [comment]
Fixed https://www.npmjs.com/package/blockcypher

**Comment by acityinohio** [comment]
Ah good catch @millette, thanks! Added it a while ago but forgot to update this issue (apologies all).
