### ISSUE TITLE
'test' net not working

### ISSUE THREAD

**Issue by yogiben** [blockcypher/node-client#12]
`main` and `test3` are working.

`test` is not at time of writing.

I get the following response `Endpoint not found. Please check your URL for typos and make sure you're using the correct  HTTP method (GET, POST, etc).`

**Comment by ArthurGerbelot** [comment]
Thank you !

**Comment by esinniobiwaquareeb** [comment]
try this, it worked for me
https://api.blockcypher.com/v1/eth/main?token=YOURTOKEN

instead of this 

https://api.blockcypher.com/v1/eth/main/addrs?token=YOURTOKEN

**Comment by adsc-cloudtec** [comment]
Make sure to select "bcy" as coin in the constructor of the blockcypher object, when you want to use the "test" chain. It doesn't work with "btc" coin.

**Comment by somvir** [comment]
use this url. see v1/beth is there instead of v1/eth
https://api.blockcypher.com/v1/beth/test/addrs?token=YOURTOKEN
