### ISSUE TITLE
getAddrsWallet method does not work when wallet name contains an space

### ISSUE THREAD

**Issue by josecelano** [blockcypher/node-client#14]
I have created a wallet with name: "test wallet" and it seems the url generated is like this:

```
https://api.blockcypher.com/v1/bcy/test/wallets/test wallet/addresses
```
It works using the url encoded version of the wallet name:

```
https://api.blockcypher.com/v1/bcy/test/wallets/test%20wallet/addresses
```

**Comment by quentinlesceller** [comment]
Seems normal no? Closing. Feel free to reopen if you feel this behaviour is abnormal.
