### ISSUE TITLE
Node client using promises

### ISSUE THREAD

**Issue by pcamarajr** [blockcypher/node-client#19]
I've wrote a version of the SDK [in my fork](https://github.com/PetrusStarken/node-client)

If it was a interesting thing for you guys and it's relevant I can make a pull request.

**Comment by govi218** [comment]
This is pretty neat but it could be even better if callbacks were optional instead of removing them altogether as per [this article](https://loige.co/to-promise-or-to-callback-that-is-the-question/).

**Comment by naro-code-lab** [comment]
Nice! Was about changing from callback to promise be.

**Comment by quentinlesceller** [comment]
Hi @PetrusStarken do you feel this should be merge into the upstream repo? I'm not very well aware if this is still relevant today (using promises instead of callback...). Thank you.

**Comment by KryptomindLLC** [comment]
Promises are more recommended and convenient to use than callback. I will suggest to replace callback with promises.

**Comment by quentinlesceller** [comment]
This is done. Closing.
