### ISSUE TITLE
Blueprint file missing

### ISSUE THREAD

**Issue by mohanad-najeeb** [blockcypher/node-client#2]
The required file "blockcypher-api-v1.md" to generate the api object is not in the repo and nowhere to be found.

**Comment by AnthonyAkentiev** [comment]
+1. It seems that the contributor of that library has working version here: https://github.com/acityinohio/node-client.git
I am sure that sooner or later he will merge that changes into the main (this one).

just do 
```
npm install 'git+https://github.com/acityinohio/node-client.git' --save
```

**Comment by acityinohio** [comment]
Changed the structure of the wrapper to be a little more lightweight; no blueprint file necessary anymore. Sorry about this before!
