### ISSUE TITLE
npm version is out of date 

### ISSUE THREAD

**Issue by MannyC** [blockcypher/node-client#23]
The version installed by npm contains old code, though the `package.json` has the "latest" 0.2, the version number doesn't seem to have been altered after recent changes.

Note that the `!error` below is a bug that was has already been [fixed](https://github.com/blockcypher/node-client/commit/3e65613607a9855c34516f171a999a81ca7d6044)
```
> npm install blockcypher@latest
> grep '!error' node_modules/blockcypher/lib/bcypher.js
		if (!error || response.statusCode !== 200) {
		if (!error || (response.statusCode !== 200 && response.statusCode !== 201)) {
		if (!error || response.statusCode !== 204) {
> grep 'version' node_modules/blockcypher/package.json
  "version"       : "0.2.0",
```

**Comment by tka85** [comment]
Can confirm this is still the case.

For the time being `npm i "git+https://git@github.com/blockcypher/node-client.git"` does the job, but would be to publish latest on npm.

**Comment by quentinlesceller** [comment]
On it.

**Comment by quentinlesceller** [comment]
0.2.1 released. Closing.
