### ISSUE TITLE
How to format a simple Node HTTPS get request against BlockCypher?

### ISSUE THREAD

**Issue by GrayedFox** [blockcypher/node-client#25]
Sorry for writing here - this is not directly related to the development of the node-client module - but I've written BlockCypher support 3 times now and haven't got a response and now I'm thinking a better approach may be to reach out to other developers familiar with BlockCypher and Node and this seemed the best place.

Apologies that this is off topic - thanks for your time :bowing_man: 

I'd like to know how to format a simple GET request against BlockCypher **using only the native Node https module**.

Example code:

```
// example options object generated from internal code
options = { hostname: 'api.blockcypher.com',
  path: '/v1/ltc/main/txs/090a0f034b2973f4e13a3a20c1acf86fcc388dff4cca99220ef0e95d176ed0f0',
  port: 443,
  method: 'GET',
  strictSSL: true }

return new Promise( (resolve, reject) => {
    https.request(options, (response) => {
      let data = ''

      console.log('statusCode:', response.status)
      console.log('headers:', response.headers)

      response.setEncoding('utf8')

      response.on('data', (chunk) => {
        data += chunk
      })

      response.on('end', () => {
        resolve(data)
      })
    }).on('error', (err) => {
      reject(err)
    })
  })
}
```
When I send a request from above I don't get any chunks back and eventually just get a socket hang up after 60 seconds. From everything I've seen in the API documentation (and looking at what request is doing inside the request NPM docs) this simple HTTPS get request should be sending a properly formatted request which matches the request formatted [here](https://github.com/blockcypher/node-client/blob/master/lib/bcypher.js#L30).

The logic for forming the param string in my code is a little different but as you can see from the example generated object, the path includes the version number for the API which should result in the same request

**Comment by quentinlesceller** [comment]
Hi @GrayedFox. Thanks for the PR. This doesn't seems directly related to BlockCypher node API. Hence I'm going to close it. Hope you found the fix though :)
