### ISSUE TITLE
Not able to access from MVC c#, but able to get result from console application.

### ISSUE THREAD

**Issue by ramsingh333** [blockcypher/node-client#26]
Hi, 

I am trying to consume blockcypher, when i try from console application c#, its fetching the result. but when i use the same in MVC web app. It's not retruning me anything, it's keeping loading all the time. didn't get back again. any idea why i am facing this.

below code i am using:

Blockcypher objmain = new Blockcypher("******************************", Endpoint.BtcTest3);
objmain.GenerateAddress().Wait();

**Comment by quentinlesceller** [comment]
Hi @ramsingh333, since this issue is quite old I'm closing it. Feel free to reopen another one if you think this is still relevant.
