### ISSUE TITLE
Websocket endpoint not working

### ISSUE THREAD

**Issue by markusait** [blockcypher/node-client#27]
I am using the Blockcypher API for test bitcoin transactions and I have troubles with the websocket API endpoint. 
When sending the regular ping object after creating a new Websocket it works fine:
```javascript
this.ws.onopen = () => {
      this.ws.send(JSON.stringify({"event": "ping"})) 
```

but when trying to check the confidence of a transaction like this we get an error

``` javascript
this.ws.onopen = () => {
      this.ws.send(JSON.stringify({event: 'tx-confidence', address:'<bitcoin address as string>', confidence:0.9}))

```

These are the references I am using are
[API reference](https://www.blockcypher.com/dev/bitcoin/?javascript#payment-forwarding)
[Event reference](https://www.blockcypher.com/dev/bitcoin/?javascript#oaptx)

Is there anything wrong with the datatypes? Any help would be great!

**Comment by Ranguna** [comment]
I can confirm this on my end too.

**Comment by ab77** [comment]
Related?
https://stackoverflow.com/questions/52275678/blockcypher-websocket-endpoint-not-working

**Comment by quentinlesceller** [comment]
You need to provide a token. Otherwise nothing will be sent.
