### ISSUE TITLE
How to sign transaction on test network?

### ISSUE THREAD

**Issue by genisgetman** [blockcypher/node-client#29]
How can i sign transactions on test network?
the [blockcypher documentation](https://www.blockcypher.com/dev/bitcoin/#creating-transactions) about transactions sending is out of date and if i try to solve it malually, has catch an error.
If i try to sign tx by another library (bitcore-explorers, bitcore-lib)
i'm getting the error around deffirence of networks. Somethink like "Address has mismatched network type".
Anybody please show me example that working for now please.

**Comment by quentinlesceller** [comment]
Thank you for the issue @genisgetman. The signer also works on test network. Feel free to reopen an issue if you are still stuck.
