### ISSUE TITLE
Can't create ETH webhook?

### ISSUE THREAD

**Issue by arnasledev** [blockcypher/node-client#30]
So this works fine with BTC but not ETH? I'm trying to create a webhook for ETH address and listen for unconfirmed transactions. With BTC this works as usual and I can see created webhook in `https://accounts.blockcypher.com/tokens/hooks/token` but when I create the same hook but initiate the `blockcypher` class with ETH -> it responds me that webhook was created but I can't find it. And it definitely wont work.

`const bcApi = new blockCypher('btc', 'main', process.env.BTC_WEBHOOKS_API_TOKEN)` - works
`const bcApi = new blockCypher('eth', 'main', process.env.BTC_WEBHOOKS_API_TOKEN)` - does not work

how to solve this?

**Comment by quentinlesceller** [comment]
Works perfectly on my end. Feel free to open an issue again but I just tested creating a web hook and this works well.
