### ISSUE TITLE
blockcypher/lib/bcypher.js:128  cb(error, body) TypeError: cb is not a function

### ISSUE THREAD

**Issue by gluneau** [blockcypher/node-client#31]
Looks like `getBlock()` is broken now.

To reproduce, just run the example in the README.md file

This repo needs an update

**Comment by quentinlesceller** [comment]
Hi @gluneau, it seems like the 0.2 tag used by npm is outdated. We will release a new version with the fix on master asap.

**Comment by quentinlesceller** [comment]
0.2.1 released. Closing.
