### ISSUE TITLE
PushTx

### ISSUE THREAD

**Issue by ekkis** [blockcypher/node-client#33]
Blockcypher makes this page available to push transactions: https://live.blockcypher.com/btc-testnet/pushtx/

I don't see a way in this module to make use of that functionality.  am I missing something?

**Comment by quentinlesceller** [comment]
See https://github.com/blockcypher/node-client/blob/master/lib/bcypher.js#L486.

**Comment by ekkis** [comment]
from looking at the code it doesn't seem that function supports the testnet?
