### ISSUE TITLE
endpoint /oap/$assetId/transfer

### ISSUE THREAD

**Issue by 1e1f** [blockcypher/node-client#4]
using Asset api on main net, getting internal error from transfer endpoint.

Also, can't use tx builder from coinprism with block cypher pushTX endpoint because coinprism signs with high-s. there a legacy mode for pushTX?

```
request = { from_private: 'xxx',
  to_address: 'akErbek7ic5u2wmSx61RsKQa6NdhDJYJVZD',
  asset_id: 'AXt4jSi1FF4uCtXQ4u1FvXpW5C9sF9zpWM',
  amount: 1 }

bcapi._post('/oap/' + request.asset_id + '/transfer', {}, request, function(error, body) {
etc . . .
}

```

from_private hidden, the source address is akJcvSJanxtVtqb1vvYA6nGwjidVTreCHyk
https://www.coinprism.info/address/akJcvSJanxtVtqb1vvYA6nGwjidVTreCHyk
error is:

```
{ error: 'Error broadcasting transfer transaction: Error pushing transaction e1a8b17dcd5a3dcd95e07e9e87f96f9da94e8b738023d65c935d49de711ef3dc: Error validating transaction: Sum of inputs 4600 lesser than outputs 5460..' }
```

**Comment by 1e1f** [comment]
I believe this is an issue with the transaction inputs and outputs when trying to build a transaction that originates from an unspent output from a coinprism transaction. Coinprism always uses 600 satoshis for the marker output, perhaps block cypher does not? I don't know if I have a way of getting the raw TX from this api so I could inspect the ins / outs

**Comment by acityinohio** [comment]
Hi @structuresound, sorry for the trouble with the API. Is this the address you're trying to send to?

https://api.blockcypher.com/v1/btc/main/oap/AXt4jSi1FF4uCtXQ4u1FvXpW5C9sF9zpWM/addrs/akErbek7ic5u2wmSx61RsKQa6NdhDJYJVZD

Normally, an issue like this has to do with the underlying UTXOs not having enough satoshis to make the resulting transfer. Do you mind sharing the public OAP address you're trying to send from? That might help me figure it out if it's just a matter of adding more staoshis to the underlying address. Feel free to also contact me via email if you want to take this off github: josh [at] blockcypher [dot com]
