### ISSUE TITLE
Hooks Endpoint not found

### ISSUE THREAD

**Issue by masonforest** [blockcypher/node-client#40]
All hooks endpoints are returning the following for me: `Endpoint not found. Please check your URL for typos and make sure you're using the correct  HTTP method (GET, POST, etc).`

```javascript
// $ TOKEN=<My Token> node index.js
// Endpoint not found. Please check your URL for typos and make sure you're using the correct  HTTP method (GET, POST, etc).
const bcypher = require('blockcypher');
var ecapi = new bcypher('eth','main', process.env.TOKEN);
var webhook = {
	event: "unconfirmed-tx",
	address: "0xAb5801a7D398351b8bE11C439e05C5B3259aeC9B",
	url: "https://my.domain.com/callbacks/new-tx"
};
ecapi.createHook(webhook, (t) => console.log(t.response.text));
```

I've tried generating a new token with no luck.

Let me know if there's anything else that would be helpful to debug. Thanks!

**Comment by matthieu** [comment]
Should be fixed now, sorry for the inconvenience.
