### ISSUE TITLE
Cannot receive wehook event

### ISSUE THREAD

**Issue by BruceChar** [blockcypher/node-client#42]
I create the new-block and confirmed-tx events webhook, which url is generated by ngrok service.
I can access the url by postman and other request tool, but I cannot receive the webhook event.

Am I wrong?
```
let hook = {
    "event": "confirmed-tx",
    // "url": "http://192.168.137.1:3721/api/test"
    "url": "https://2ea43af3c8bd.ngrok.io/btc/cb"
  }
  bcapi.createHook(hook, (err, data) => {
    if (err !== null) {
      console.error("hook error:", err);
    } else {
      console.log(data)
    }
  })
```
the webhook is create successfully!
How can I test the event!

**Comment by quentinlesceller** [comment]
You have to specify an address? The server will send a callback on your URL every time there is a confirmed tx on the address you specified.
